### ISSUE TITLE
Provide better feedback on unfulfilled constraints.

### ISSUE THREAD

**Issue by MicahZoltu** [Zoltu/RepoCreator-Client#9]
In several places there are constraints before a button is clickable.  e.g., Repo search, name choice, repo creation.  Use [Aurelia Validation](https://github.com/aurelia/validation) plugin to validate input and provide feedback to the user.

**Comment by duahaudo** [comment]
Hi, what we need to do with this job ?

**Comment by MicahZoltu** [comment]
![image](https://cloud.githubusercontent.com/assets/886059/10237892/09f1d072-686d-11e5-89e3-3069ba23062f.png)

On this page, the `Submit` button is disabled but there is no feedback to the user as to why it is disabled.  The `Submit` button should give feedback when clicked instead of being disabled by using the [Aurelia Validation](https://github.com/aurelia/validation) plugin like the `Blog post example` at the [Aurelia Validation Examples](http://aurelia.io/validation/) page.

The same for the magnifying glass button on the repo-chooser (first) page and the `Create` button on the replacements (third) page.  Just like in the blog post example, the text boxes should highlight and text should be displayed near them indicating what the problem was.

**Comment by duahaudo** [comment]
Hi Zoltu, I cann't find the magnifying glass button bon the first page. I don't know validation rule for the `Create` button on the third page too. What do you want next to finish the first milestone?

**Comment by MicahZoltu** [comment]
The magnifying glass I am referring to is the one in the search area of the "choose a template" step:
![image](https://cloud.githubusercontent.com/assets/886059/10418026/a29dab68-7004-11e5-88ab-f1b6210fbd5f.png)

The only validation necessary for the search button is that the search field is not empty.

For the `Create` button the validation is that all of the fields are filled in.  Right now the button is disabled until you fill in all of the fileds but the user experience is fairly poor.

**Comment by MicahZoltu** [comment]
Fixed in #25.
